doc.type. html
html lang en 
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’covid strings 6’ 
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=#background overview
heading2=#functions
heading3=background code 
<header.html>
background overview
background for covid strings6
filename=covid strings6 background .js
java.awt graphics 
img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=documentgetelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio (audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new j button (change color)
public fun with graphics()
color panel=new j panel();
add(panel,center )
button panel=
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionListener(new action listener)
override 
public actionperformed(actionevent e)
random r= newRandom();
<header.html>
background functions
functions used in covid strings6 background
colorpanel.setbackground(rnextint(thirteen),(rnextint(thirteen)),(rnextint(thirteen),(rnextint(thirteen),(rnextint(thirteen),(rnextint(thirteen),(rnextint(thirteen),)(rnextint(thirteen),(rnextint(thirteen)), (rnextint(thirteen)), (rnextint(thirteen)), (rnextint(thirteen)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
<header.html>
background code 
code to program game background
public  actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonPanel, borderlayout.South)
public static  main(string [] args)
jframe f = new covid strings6()
f.set title(covid strings6)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if(mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
private j button next button=new jbutton(next)
nextbutton add.actionlistener(this)
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
object keys(team)
entries object entries(obj);
value object=[team color]
return filename
