doc.type html
script
html 
head
utf eight
viewport content=width=device-width, initial-scale=one
title covid strings6 first round bracket 
div id bracket class bracket div
script src bracket.js
link rel= stylesheet href=css
head
body
html
bracket
matchup
solid zero
filename= covid strings 6 first round .js
first round=(highest overall seed ,second highest seed third highest seed first middle seed, second middle seed,  third lowest seed ,second lowest seed,lowest overall seed)
highest overall seed = 1 seed
second highest seed=2 seed
third highest seed=3 seed
firstmiddleseed=4seed
second middle seed = 5 seed
third lowest seed= 6 seed
second lowest seed = 7 seed
lowest overall seed = 8 seed
document.addeventlistener(domcontentloaded, () => {
bracket =document.getelementbyid(bracket)
teams=[magenta,burgundy,red,indigo,orange,green,black,white]
matchup1=(green versus red )
matchup =document.createelement(div);
matchup.classlist.add(matchup);
matchup.inner html =<div>${team1}</div><div>${team2}</div>;
return matchup;
matchup2=(white versus magenta magnetizers)
matchup.classlist.add(matchup);
matchup.inner html = <div>${team1}</div><div>${team2}</div>;
return matchup;
matchup3=(indigo versus orange)
matchup.classlist.add(matchup);
matchup.inner html =<div>${team1}</div><div>${team2}</div>;
return matchup;
matchup4=(black verus burgundy)
matchup.classlist.add(matchup);
matchup.innerHTML =<div>${team1}</div><div>${team2}</div>;
return matchup;
if (event.target.classlist.contains(team)) 
return matchup
else:
add matchup
createround =covid strings6 first round
round =document.createelement(div);
round.classlist.add(round);
for (let i = zero; i < teams.length; i += two) {
round.appendchild(creatematchup(teams[i], teams[i+one]));
return round;
bracket.appendchild(createround(teams));
matchup.inner html =div class=team>${team1}</div><div class=team>${team2}</div>;
java util.scanner
java.util
questions[]questions={
collections.shuffle(arrays.aslist(questions)
question1
question2
question3
question4
question5
question6
question7
question8
question9 
question10
question11 
question12
question13
question14 
question15
question16
question17
question18 
team.addeventlistener(click, () => {
team.classlist.toggle(selected)
advancingteams=(currentteams)
result=declarewinner(matchup1)
if red score>=forty:
console.log(red protein spikers win)
else:
console.log(green peacemakers win)
result=declarewinner(matchup2)
if magenta score>=forty:
console.log(magenta magnetizers win)
else:
console.log(white transit angels win)
result=declarewinner(matchup3)
if orange score>=forty:
console.log(orange rna messengers win)
else:
console.log(indigo isos win)
result=declarewinner(matchup4)
if burgundy score>=forty:
console.log(burgundy rebuilders win)
else:
console.log(black night riders win)
return filename
