doc.type.html
script
filename=covid strings6.js
java.awt graphics 
thisimg=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
div id=header/div
audio=new audio(audio_file mp3)
audio.play 
random button
new button (set random color)
private final j button option button=
new  button (change color)
public fun with graphics()
color panel=new j panel();
add (panel,center )
jpanel button panel=
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e){
random r= newrandom();
colorpanel.setbackground(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),(rnextint(thirteen)),(rnextint(thirteen))), (rnextint(thirteen)), (rnextint(thirteen)),(rnextint(thirteen)))
num teams
total players= players per team
if players per team=0
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener(){
override 
public actionperformed(actionevent e){
color m=jcolorchooser.showdialog(funwithgraphics.this,))
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args){
jframe f = new covid strings6()
f.set title(covid strings6)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblScore)
lbl.score.inner html=score
private j button next  button=new jbutton(next)
nextbutton add.actionlistener(this)
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a :one,b :two, c:three, d:four, e:five, f:six, g: seven , h: eight}
object keys(team)
objectentries(obj);
value object=[team color]
covidstringsteamlist6= [magenta magnetizers,burgundy rebuilders,red protein spikers,indigo isos,orange rna messengers,green peacemakers ,black night riders,white transit angels]
covidstringsphraselist6=[non-concatenated myocarditis does have serious implications given there is some relationship with covid
however new research says that among college athletes myocarditis is not related to covid
the very rare instances of vaccinated people getting myocarditis should not deter vaccination
just as much as health effects are still unfolding so are economic effects
particularly the most extreme case is china
the state of the us economy is nothing short of miraculous 
unfortunately, taylor swift and beyonce can not do it all by themselves
this also hides confusion over how the labor market responds
concatenated strings
the+way+the+economy+bounces+back+depends+on+multiple+factors
even+so+the+us+has+some+exceptions
economic+and+healthcare+inequities+stand+out
a+different+thing+that+stands+out+is+the+claim+that+china+caused+it+to+elect+joe+biden
even+if+this+was+true+it+does+not+mean+it+was+planned+in+advance
covid+still+was+an+issue+that+biden+has+to+deal+with
one+solution+was+the+one hundred+million+shots+in+one hundred+days
this+goal+was+achieved+within+fifty+eight+days]
covidstrings6multiplechoicelist=[1:a snow b heart attacks c myocarditis d chili dogs,2:a democracy b stock market c black eyed peas d economy, 3: a college athletes b triathletes c flag football players d power slammers,
4:a the us b china c south vietnam d malaysia, 5: a eighty-eight b eight hundred eight c five hundred twenty five thousand d one hundred million, 6: a infinitesimal b extremely common c very rare d world beating,
7: a loss of learning b long covid  c trump effects d economic effects, 8: a problematic b extreme c optimistic d straightforward, 9: a canadian b danish c belgian d us,
10: a race b healthcare c internet d covid, 11: a russia b the european union c mexico d china, 12: a ice spice b jay-z c taylor swift d young thug,
13: a leaked b centrally planned  c undermined d planned, 14:a obama b kamala harris c jeb bush d biden, 15: a doj responds to trump stealing classified documents b why it took one hundred twenty three times to confirm the first black woman supreme court justice c the labor market d china responds to covid coverup accusations,
16: a your buddy b a covid vaccine c a heroin needle d donald trump, 17: a long covid b redlining c slavery reparations d inflation, 18: a myocarditis b a loss of smell c how tired you are d how bad the mar-a-lago case is,
19: a wishful thinking b american exceptionalism c people moving on from the lockdown d people with money to spend, 20: a yes b no]
covidstrings6mathproblemslist=[there are currently five million vaccines that have been administered over the past two months starting in december twenty-twenty  if  the cdc says that there was a supply shortage of approximately one hundred fifty thousand doses would it be possible for one hundred million vaccines delivered by the end of may twenty-twenty one if a study showed that more racial minorities are more likely not only to mistrust getting treated but also sixty percent more likely to have complications from covid what could be done policy-wise to deal with this issue?,if the one hundred fifty thousand missing vaccines have been found how much is the new supply and can bidens goal be reached?,if the white house covid advisory board says that production needs to increase to twenty million vaccines per month to meet the goal how many more vaccines are needed?,if there eventually was a surplus of one hundred thousand vaccines what should the biden administrations strategy be?
if+one+study+showed+that+taylor+swift+was+the+covid+economy+savoir+due+to+the+three hundred+percent+increase+how+much+money+would+be+gained+if+the+us
+economy+had+threehundred+trillion+dollars+before?,if+the+same+study+found+that+afterwards+there+was+a+fifty+percent+decrease+how+much+would+the+us+economy+lose?,if+a+poll+found+that+fifty two+percent+of+people+think+that+there+is+no+evidence+supporting+the+idea+that+vaccines+cause+heart+problems+what+percent+do?,if+twenty-eight+percent+say+that+they+believe+it+causes+heart+problems+because+they+read+something+online+what+is+the+remaining+percent,if+thirty-six+percent+of+nos+strongly+believe+theres+no+evidence+for+covid+and+myocarditis+what+percent+are+mild?,if+the+twenty-eight+percent+of+nos+are+open+to+changing+their+mind+what+would+the+new+yes+percent+be?]
covidstrings6sentencelist=[it is statistically improbable that anyone would get myocarditis from a covid vaccine, the post covid economy growing is one good sign of american exceptionalism,racism+should+not+be+an+excuse+to+ignore+long+covid+with+minorities chili+dogs+have+no+relation+to+myocarditis  ]
string.split   
arrays.aslist(list<string>)
for (string ss:arr){
system.outprintin(ss)
java util.scanner
java.util
questions[]questions={
collections.shuffle(arrays.aslist(questions)
question.bonus1=(would+the+meaning+of+the+sentence+change+if+the+term+post+covid+was+removed)
if math problem== x percent:
subtract exact from one hundred
if math problem== margin of error:
add and subtract exact 
else:
remain constant
userin.select team
import meta.
class myclass
constructor (non-concatenated)
return category
if category==math problem:
type answer
else:
select from multiple choice
myclass=new.myclass(concatenated)
return category
if category==math problem:
type answer
else:
select from multiple choice
import syntax 
substring(start,end)
userin.multiple choice
if selectedanswer==correct answer:
return true
else:
return false
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet)
if users team wins covid strings6 
console log users team wins covid strings6 
else
return game over
return filename
